### ISSUE TITLE
[FEATURE] Read from stdin

### ISSUE THREAD

**Issue by CrossNox** [hadialqattan/pycln#117]
In order to add `pycln` as an `ALE` fixer using `nvim`, IIRC, I'd need `pycln` to be able to format files from stdin.

Very much like `black` does:
```bash
cat some_file.py | black -
```

Other than my niche use case, I think this would be a great addition for some other people.

**Comment by hadialqattan** [comment]
Hi @CrossNox , it's a good idea, I will implement that as soon as possible...

I'm happy to see you around...Thank you.

**Comment by hadialqattan** [comment]
@CrossNox if you don't mind, please try out the [i117](https://github.com/hadialqattan/pycln/tree/i117 ) branch and let me know if we are good to go.

**Comment by CrossNox** [comment]
@hadialqattan looks great, thanks! (Sorry for the delay)
