### ISSUE TITLE
[BUG] File Read Error When Running pycln

### ISSUE THREAD

**Issue by MrBeeMovie** [hadialqattan/pycln#119]
**Description** 
When checking the "project".pth file in virtual environment pycln is appending /__init__.py to the filename instead of the contents.

**To Reproduce**

1. Run:
>$ pycln project_name/

within poetry created virtual environment that exists in project directory

2. Error traceback:

`  /Users/user/Documents/repos/repo/.venv/lib/python3.7/site-packages/repo.pth/__init__.py Permission denied [READ] [Errno 13] ⛔`

3. I believe this is happening because contents of repo.pth should be used:
`/Users/user/Documents/repos/repo`

**Expected behavior**:

`/Users/user/Documents/repos/repo/__init__.py`
should be opened for reading not
`/Users/user/Documents/repos/repo/.venv/lib/python3.7/site-packages/repo.pth/__init__.py`

**Environment:**

- Python Version: 3.7
- Pycln Version: 1.2.5
- OS Type: MacOS

**Additional context**
I changed the username in path and project name for confidentiality reasons. If this is happening because of my misunderstanding of pycln usage please let me know. Thank you for your understanding.

**Comment by hadialqattan** [comment]
Hi @MrBeeMovie, this is my first time facing the `.pth` files. Also, I believe this type of usage is very rare. I'll fix this issue as soon as possible, but for the time being, please consider using the `-a/--all` flag so Pycln would skip the part containing the broken code.

Thanks for reporting this issue. I'm happy to see you around.

**Comment by MrBeeMovie** [comment]
No problem. Thank you for your hard work! I use poetry to manage the project's dependencies so I believe that is what creates this .pth file but not entirely sure. Thanks again!!!
