### ISSUE TITLE
[BUG] non-typing subscriptable types (e.g. Django's QuerySet) are not supported.

### ISSUE THREAD

**Issue by uptickmetachu** [hadialqattan/pycln#125]
**Describe the bug**  Semi string type hints being removed when the type is not a built in type variable as defined in https://github.com/hadialqattan/pycln/pull/36/files

**To Reproduce** Steps to reproduce the behavior:

1. Take this code snippet:

   ```python 
    # cats.py
    from django.models import QuerySet
    from typing import TYPE_CHECKING
    
    if TYPE_CHECKING:
        from .models import Cat
    
    def make_cats_meow(cat_queryset: QuerySet["Cat"]) -> None:
        pass
   ```

2. Run this Pycln command:
   ```bash
   pycln -a cats.py
   ```
3. Error traceback or unexpected output (if present):

   ```bash
    cats3.py:5:4 'from .models import Cat' was removed! 🔮
    cats.py 1 import was removed! 🚀

   ```

4. Unexpected fixed code (if present):

   >

   ```python
    from django.models import QuerySet
    from typing import TYPE_CHECKING
    
    if TYPE_CHECKING:
        pass
    
    def make_cats_meow(cat_queryset: QuerySet["Cat"]) -> None:
        pass
   ```

**Expected behavior**:

1.  Description: A clear and concise description of what you expected to happen.

I expect Cat to not be removed

2.  Expected output (if present):
**Environment (please complete the following informations):**

- Python Version: Python 3.10
- Pycln Version: v1.3.1
- OS Type: MacOS

**Additional context** 
Only the built in types from https://github.com/hadialqattan/pycln/pull/36/files are supported.
Other subscriptable types aka `QuerySet` from django are not.

**Comment by hadialqattan** [comment]
Hi @uptickmetachu, this problem cannot be solved directly because there's no such a way to distinguish regular `dict` subscriptions from the type hinting subscriptables statically (as far as I know)...

(1)
```python3
from django.models import QuerySet
from typing import TYPE_CHECKING
 
if TYPE_CHECKING:
    from .models import Cat

# Real type-hinting
CatsQuerySetType = QuerySet["Cat"]

def make_cats_meow(cat_queryset: QuerySet["Cat"]) -> None:
    pass
```

(2)
```python3
from typing import TYPE_CHECKING
 
if TYPE_CHECKING:
    from .models import Cat

# Dictionary calls
QuerySet = {"Cat": "something-else"}

CatsQuerySetType = QuerySet["Cat"]

def make_cats_meow(cat_queryset: QuerySet["Cat"]) -> None:
    pass
```

(3) even worse
```python3
from dummy_dictionaries import QuerySet
from typing import TYPE_CHECKING
 
if TYPE_CHECKING:
    from .models import Cat

# Dictionary calls because this time QuerySet is a dictionary!
CatsQuerySetType = QuerySet["Cat"]

def make_cats_meow(cat_queryset: QuerySet["Cat"]) -> None:
    pass
```

Therefore, there's no way to be 100% sure if it's a type-hint or a dictionary subscription using static analysis for each file individually (this is possible but requires significant changes and may make Pycln much slower which is not an option when it comes to this rare situation + other static analysis tool behave just like Pycln).

So the only way to do it safely is to add `Django` subscriptables just like we did with typing subscriptables.

**Comment by hadialqattan** [comment]
@uptickmetachu for now you can solve this problem by using one of the import skipping options:
- [Skipping a single import](https://hadialqattan.github.io/pycln/#/?id=import-skip)
- [Skipping a module/package/library globally](https://hadialqattan.github.io/pycln/#/?id=-skip-imports-option)

---
For the first option (in our case):
```python3
# cats.py
from django.models import QuerySet
from typing import TYPE_CHECKING
 
if TYPE_CHECKING:
    # we can use either `# nopycln: import` or `# noqa`:
    from .models import Cat  # nopycln: import
 
def make_cats_meow(cat_queryset: QuerySet["Cat"]) -> None:
    pass
```
For the second option:
```bash
$ pycln cats.py --skip-imports models  # even if this module has been imported into other files, it would be skipped.
```

**Comment by hadialqattan** [comment]
\+ if you didn't like both options, you can use `'QuerySet["Cat"]'` format instead of `QuerySet["Cat"]`.

**Comment by hadialqattan** [comment]
@uptickmetachu I'm sorry for making it too long...

Anyway, in case you agree with the idea of adding Django's subscriptable types just like we did with typing's subscriptable, please let me know so we can work on it [if you don't mind] (I'm not a Django user).

**Comment by uptickmetachu** [comment]
No worries @hadialqattan !

I'm very happy with your workaround.

Making the entire type string based as follows works perfectly. Mypy types it properly and pycln does not remove the import anymore. Thank you for your quick reply!

```python
def make_cats_meow(cat_queryset: "QuerySet[Cat]") -> None:
    pass
```

**Comment by hadialqattan** [comment]
> No worries @hadialqattan !
> 
> I'm very happy with your workaround.
> 
> Making the entire type string based as follows works perfectly. Mypy types it properly and pycln does not remove the import anymore. Thank you for your quick reply!
> 
> ```python
> def make_cats_meow(cat_queryset: "QuerySet[Cat]") -> None:
>     pass
> ```

I'm glad I was able to help. Thanks for being around!
