### ISSUE TITLE
unexpected error on archlinux

### ISSUE THREAD

**Issue by ornariece** [hadialqattan/pycln#136]
``/usr/lib/python3.10/lib-dynload/math.cpython-310-x86_64-linux-gnu.so/__init__.py Permission denied [READ] [Errno 13]``
hi, i'm getting this error, and the only thing i can tell is that ``/usr/lib/python3.10/lib-dynload/math.cpython-310-x86_64-linux-gnu.so`` is a file.
my user has permissions over this directory

**Comment by hadialqattan** [comment]
Hi @ornariece, could you please provide me more info about the code you were trying to format? (a similar example)

**Comment by hadialqattan** [comment]
Also, I need the command you wrote to run Pycln, please.

**Comment by hadialqattan** [comment]
I need both info because the code example will provide me the case, while the command will tell me the thing that Pycln was trying to do.

**Comment by ornariece** [comment]
yea i figured you were gonna ask for more info, but i don't have any really. i've isolated the problem, on a specific sub-package of my project (running a simple ``pycln sub-package_name`` command), but when running pycln on each file in that directory i don't get any error. only when running on the directory do i get the error (and i can't share the whole sub-package with you :/)

**Comment by hadialqattan** [comment]
> yea i figured you were gonna ask for more info, but i don't have any really. i've isolated the problem, on a specific sub-package of my project (running a simple ``pycln sub-package_name`` command), but when running pycln on each file in that directory i don't get any error. only when running on the directory do i get the error (and i can't share the whole sub-package with you :/)

Kindly, try to use the `--all` flag and let me know weather the problem persist or not.

**Comment by hadialqattan** [comment]
@ornariece, kindly, could you test the master branch against the same case?
