### ISSUE TITLE
[BUG] --check and --diff don't work together

### ISSUE THREAD

**Issue by raphCode** [hadialqattan/pycln#146]
**Describe the bug**
The flags `--check` and `--diff` should work together, returning the correct exit code like with `--check` alone, and the diff output like with `--diff`.
This would replicate the behavior of tools like `black` and `isort` where both flags can be combined as expected. An application for this would be a pre-commit hook so that commits with unnecessary imports can be declined and the pycln diff explains why.

**To Reproduce**

1. Take this code snippet:

```python
import math
```

2. Run this Pycln command:
```bash
$ pycln --check --diff
```
3. unexpected output (if present):

```bash

All done! 💪 😎
1 import would be removed, 1 file would be changed.
$ echo $?
1
```
**Expected behavior**:

1.  Description: Shows diff and returns 1 as exit code
2.  Expected output (if present):

```bash
--- original/ test.py
+++ fixed/ test.py
@@ -1 +0,0 @@
-import math



All done! 💪 😎
1 import would be removed, 1 file would be changed.
$ echo $?
1
```

**Environment (please complete the following informations):**

- Python Version: 3.10.5
- Pycln Version: 1.3.5
- OS Type: Arch Linux

**Comment by hadialqattan** [comment]
This is a good catch @raphCode!

**Comment by hadialqattan** [comment]
@raphCode I'm working on a PR fixing this bug...

Thanks a lot for being around and supporting the project by reporting this bug.

**Comment by raphCode** [comment]
Thanks for the prompt fix and this project which keeps the imports clean on my projects! :)
