### ISSUE TITLE
[BUG] Type checking import removed when with library generic types

### ISSUE THREAD

**Issue by Kaelten** [hadialqattan/pycln#154]
**Describe the bug** 

When using a library with a generic type (in my case sqlalchemy's `Mapped` type) pycln is removing in-use type checking imports.

I've tested with a few variations, here's what I found:
*  `'OtherClass'` works fine
* `dict['OtherClass']` works fine
* `Mapped['OtherClass']` is not recognized and the import is removed

**To Reproduce** Steps to reproduce the behavior:

I've taken my sqlalchemy model definition and reduced it down to the smallest reproducible case I could and then changed names around to avoid leaking codebase details. 

```python
import typing

from sqlalchemy.orm import Mapped

if typing.TYPE_CHECKING:
    from project import OtherClass


class Object:
    other: Mapped['OtherClass']
```

Used this command

 ```bash
 $ pycln --all <file>.py
 ```

Resulted in this unexpected code:

```python
import typing

from sqlalchemy.orm import Mapped

if typing.TYPE_CHECKING:
    pass


class Object:
    other: Mapped['OtherClass']
```

**Expected behavior**:

1.  Description: A clear and concise description of what you expected to happen.
  I expect that this would not remove the output

**Environment (please complete the following informations):**

- Python Version: 3.10
- Pycln Version: 2.0.2
- OS Type: macos

**Comment by hadialqattan** [comment]
A good catch @Kaelten!

This bug should've been fixed before in PR #36, but, unfortunately, the approach was partially wrong (only supports the built-in type annotations).

**Comment by hadialqattan** [comment]
\+ @Kaelten thanks for supporting the project by reporting this bug 🌹.

**Comment by hadialqattan** [comment]
@Kaelten if you don't mind, could you test the main branch against your case?

**Comment by Kaelten** [comment]
@hadialqattan I've tested with 2.0.3 and I no longer get the file removed, however pycln now is erroring for me as described in #161
