### ISSUE TITLE
Typo: wrong `CHANGELOG.md` links in `docs/CONTRIBUTING.md`

### ISSUE THREAD

**Issue by Yokozuna59** [hadialqattan/pycln#157]
In [docs/CONTRIBUTING.md](https://github.com/hadialqattan/pycln/blob/master/docs/CONTRIBUTING.md) line [119](https://github.com/hadialqattan/pycln/blob/master/docs/CONTRIBUTING.md?plain=1#L119), the link of `CHANGELOG.md` isn't same as it's should be, it's just `CHANGELOG` rather than `CHANGELOG.md`, which redirect the user to undefined GitHub page.

**Comment by hadialqattan** [comment]
@Yokozuna59 I'm happy to see you supporting the project... a PR for fixing this typo is most welcome.

**Comment by hadialqattan** [comment]
BTW, a simple and quick PR here is more than enough. No need for reading the contribution guidelines for a typo fix.
