### ISSUE TITLE
(📚) Add a pronunciation guide to the readme

### ISSUE THREAD

**Issue by KotlinIsland** [hadialqattan/pycln#163]
Is it "py clean"?

**Comment by hadialqattan** [comment]
> Is it "py clean"?

It's "py-klin". Thanks for the suggestion, but isn't it too much to add a pronunciation to the docs? 😅

**Comment by KotlinIsland** [comment]
Personally when I see a project with an ambiguous name the very first thing I do is want to know how to pronounce it. I've seen other projects that have a pronunciation guide.

**Comment by hadialqattan** [comment]
> Personally when I see a project with an ambiguous name the very first thing I do is want to know how to pronounce it. I've seen other projects that have a pronunciation guide.

If you don't mind, could you open a PR adding Pycln's pronunciation wherever you think it should be?
(we have two different `README.md` files, one at the root dir (for GitHub) and another in the `docs/` dir (for docs pages)).

BTW, you don't have to go throw the contribution guidelines for such a PR, open it the way you want and I'm gonna help you finalize it.

\+ Thanks a lot for supporting the project 🌹.

**Comment by hadialqattan** [comment]
I'm gonna close this issue as it's not mandatory, please feel free to open a PR if you want to.
