### ISSUE TITLE
[BUG] cleaned imports used in generics and wrapped in string

### ISSUE THREAD

**Issue by Goldziher** [hadialqattan/pycln#169]
```python
from typing import (
    TYPE_CHECKING,
    Generic,
    TypeVar,
    cast
)

if TYPE_CHECKING:
    from starlite.handlers.http import HTTPRouteHandler

Handler = TypeVar("Handler")


class RouteHandlerMixin(Generic[Handler]):
    scope: "Scope"

    @property
    def route_handler(self) -> Handler:
        """
        Returns:
            The target route handler
        """
        return cast("Handler", self.scope["route_handler"])


class Request(RouteHandlerMixin["HTTPRouteHandler"]):
    ...
```

In the above example the import in the `TYPE_CHECKING` block will be removed.

**Comment by hadialqattan** [comment]
@Goldziher thanks for reporting this bug, I'll look into it asap.

**Comment by hadialqattan** [comment]
Hi again @Goldziher, I've fixed this bug, and the fix will be available in the next release. Thanks again!

**Comment by Goldziher** [comment]
awesome

**Comment by Goldziher** [comment]
@hadialqattan -- may i suggest, lint for redundant pycln ignore comments and redundant noqa comments that affect it.

**Comment by hadialqattan** [comment]
@Goldziher -- Sure, do you mean something like `--ignore-noqa-comments`?

**Comment by hadialqattan** [comment]
if so, could you suggest a better flag name? (if any)

**Comment by Goldziher** [comment]
> @Goldziher -- Sure, do you mean something like `--ignore-noqa-comments`?

i meant something like raise an error if a `noqa` comment is not required. There is such a setting in `flake8`, `pylint` and `mypy`
