### ISSUE TITLE
Security Disclosure

### ISSUE THREAD

**Issue by asottile** [hadialqattan/pycln#17]
Where do I report a security bug?

**Comment by hadialqattan** [comment]
Unfortunately, I forgot it, I'm gonna include a security reporting policy section in the docs.

Thanks a lot!

**Comment by asottile** [comment]
no I mean I have a security bug, is there somewhere I can reach out to you about it

**Comment by hadialqattan** [comment]
If it's a high risk vulnerability, please report it to <alqattanhadizaki@gmail.com>, otherwise, kindly open another issue.

**Comment by hadialqattan** [comment]
@asottile I'm waiting for your report, thanks again.
