### ISSUE TITLE
[FEATURE] Release on conda-forge

### ISSUE THREAD

**Issue by AlexisFetet** [hadialqattan/pycln#173]
Currently setting pycln in conda environments requires to use pip, which reduces interoperability.

pre-commit with conda requires dependancies to be available with [conda install](https://github.com/pre-commit/pre-commit/blob/5840635baa7642a2be4e1de335f7ba9df2a7bc7b/pre_commit/languages/conda.py#L81).

Pycln can only be installed for pre-commit with the environment.yml file, which does not allow for pre-made hooks to be created without pycln in all environments even if not used, or for user to add pycln as a dependency.

**Comment by hadialqattan** [comment]
Thank you for the suggestion. I'll work on this as soon as I get time for Pycln 👍🏻.

**Comment by hadialqattan** [comment]
UPDATES: I've created a recipe PR for adding Pycln to the conda-forge channel [[see PR#20969](https://github.com/conda-forge/staged-recipes/pull/20969)].

**Comment by AlexisFetet** [comment]
Thanks for the quick PR, I see it's just missing the validation from maintainers 👍

**Comment by hadialqattan** [comment]
Hi again @AlexisFetet, the [PR](https://github.com/conda-forge/staged-recipes/pull/20969) has been merged. Now [Pycln is available on conda-forge](https://github.com/conda-forge/pycln-feedstock)!
