### ISSUE TITLE
Release new version with different upper limit for typer package

### ISSUE THREAD

**Issue by williamjamir** [hadialqattan/pycln#179]
I'm currently using pycln 2.1.1, which has an upper limit to typer for version 0.6.

Would it be possible to release a new version of pycln, which supports typer v0.7? 
(I saw that the PR was already merged, only needs a new version).

Also, just out of curiosity, why pycln cannot have the typer package version set as ">=0.4.1" only?

**Comment by hadialqattan** [comment]
Luckily, a new version is scheduled today (`v2.1.2`)... I'm setting an upper limit to ensure that newer versions are compatible before letting the users use them.

**Comment by hadialqattan** [comment]
I'll close this issue as soon as I release the next version. Please feel free to continue the discussion.

**Comment by hadialqattan** [comment]
`v2.1.2` has been released and it contains the fix.
