### ISSUE TITLE
[BUG] References in TypeAlias are not recognized which act as a str

### ISSUE THREAD

**Issue by GreyElaina** [hadialqattan/pycln#185]
**Describe the bug**

`pycln` cannot recognize these references in TypeAlias, which brings unexpected "unused" import removed.

**To Reproduce**

1. Take this code snippet:

	```py
	from typing import MutableMapping
	from typing_extensions import TypeAlias

	A: TypeAlias = "MutableMapping[str, int]"

	def a(x: A) -> int:
	    ...

	...# other part of this program
	```

2. Run this Pycln command:
   ```bash
   $ pycln program.py
   ```
3. Error traceback or unexpected output (if present):

   ```bash
	program.py:1:0 'from typing import MutableMapping' was removed! 🔮
  	program.py 1 import was removed! 🚀

	All done! 💪 😎
	1 import was removed, 1 file was changed.
   ```

4. Unexpected fixed code (if present):

   >

   ```python
	from typing_extensions import TypeAlias

	A: TypeAlias = "MutableMapping[str, int]"  # pyright reports '"MutableMapping" is not defined'
   ```

**Expected behavior**:

1.  Description: pycln won't clear these references in TypeAlias which described as a string.
2.  Expected output (if present):

    ```bash
    Looks good! ✨ 🍰 ✨
    1 file left unchanged.
    ```

3.  Expected fixed code (if present):

    >

    ```py
	from typing import MutableMapping
	from typing_extensions import TypeAlias

	A: TypeAlias = "MutableMapping[str, int]"

	def a(x: A) -> int:
	    ...

	...# other part of this program
	```

**Environment (please complete the following informations):**

- Python Version: 3.9.10 in pdm's venv
- Pycln Version: v2.1.2
- OS Type: Windows 10

**Additional context**

None

**Comment by hadialqattan** [comment]
Hi @GreyElaina, I've just shipped a PR(#190) that has the fix.

Thanks for reporting the bug.
