### ISSUE TITLE
[BUG] Module not found when package installed in editable mode from path

### ISSUE THREAD

**Issue by yodaldevoid** [hadialqattan/pycln#192]
**Describe the bug** A clear and concise description of what the bug is.

When running `pycln` on a project with a dependency installed from a local path in editable mode `pycln` is unable to find the module.

**To Reproduce** Steps to reproduce the behavior:

1. Setup:

   Make the sub_package.
   ```bash
   $ mkdir first_project
   $ mkdir first_project/sub_package
   $ touch first_project/sub_package/__init__.py
   $ printf "[project]\nname = \"sub_package\"\nversion = \"1.0.0\"\n[build-system]\nrequires = [\"pdm-backend\"]\nbuild-backend = \"pdm.backend\"" > first_project/pyproject.toml
   ```

   Make the super_package.
   ```bash
   $ mkdir second_project
   $ mkdir second_project/super_package
   $ echo "from sub_package import *" > second_project/super_package/__init__.py
   ```

   Create a virtual environment and install everything we need.
   ```bash
   $ cd second_project
   $ python3 -m venv .venv
   $ source .venv/bin/activate
   $ python3 -m pip install pycln
   $ python3 -m pip install -e ../first_project
   ```

2. Run this Pycln command while in the virtual environment in the "second_project" directory:
   ```bash
   $ pycln .
   ```
3. Error traceback or unexpected output:

   ```bash
     super_package/__init__.py:1:0 UnexpandableImportStar: 'sub_package' module not found or it's a C wrapped module! ⛔
   
   Oh no, there was an error! 💔 ☹️
   1 file left unchanged, 1 file has failed to be cleaned.
   ```

**Expected behavior**:

1.  Description: `pycln` should remove the unused `from sub_project import *` statement.

**Environment (please complete the following informations):**

- Python Version: 3.10.6
- Pycln Version: 2.1.3
- OS Type: Windows 10 and Ubuntu Linux

**Additional context** Add any other context about the problem here.

**Comment by hadialqattan** [comment]
@yodaldevoid I've opened a PR(#200) having the fixing.. if you don't mind could you verify that it works?

Thank you for your support.
