### ISSUE TITLE
Pathspec dependency is incompatible with djlint

### ISSUE THREAD

**Issue by cbradl01** [hadialqattan/pycln#196]
**Describe the issue**

When attempting to upgrade djlint via `Poetry update`, the resulting message below shows that pycln's pathspec dependency is incompatible with djlint's pathspec dependency. It would be great if pycln's pathspec dependency could be upgraded.

`Because pycln (2.1.3) depends on pathspec (>=0.9.0,<0.11.0)
 and djlint (1.27.0) depends on pathspec (>=0.11.0,<0.12.0), pycln (2.1.3) is incompatible with djlint (1.27.0).
So, because bps-code-control depends on both djlint (1.27.0) and pycln (2.1.3), version solving failed.`

**Environment:**

- Python Version: 3.10
- Pycln Version: 2.1.3
- OS Type: macOS Ventura

**Comment by hadialqattan** [comment]
@cbradl01 I've provided a fix.. thanks for reporting the issue. the fix will be available in the next release soon-ish.

**Comment by JelleZijlstra** [comment]
I think this actually makes it worse, you now depend on:
```
    pycln 2.1.4 depends on pathspec<0.10.0 and >=0.9.0
```

This is causing problems for us at python/typeshed#10243 because we require `pathspec>=0.10.3`. I think for now I'll stick to pycln 2.1.3.

**Comment by hadialqattan** [comment]
> I think this actually makes it worse, you now depend on:
> 
> ```
>     pycln 2.1.4 depends on pathspec<0.10.0 and >=0.9.0
> ```
> 
> This is causing problems for us at [python/typeshed#10243](https://github.com/python/typeshed/pull/10243) because we require `pathspec>=0.10.3`. I think for now I'll stick to pycln 2.1.3.

I apologize.. I'll make a quick release with a `pathspec<0.12.0 and >=0.9.0`, which I believe would fix the problem.

**Comment by JelleZijlstra** [comment]
Thanks, no worries!

**Comment by hadialqattan** [comment]
> Thanks, no worries!

v2.1.5 has been released. Thank you for your support.
