### ISSUE TITLE
[BUG] `pycln --all` removes an implicit import from a subpackage

### ISSUE THREAD

**Issue by adamchainz** [hadialqattan/pycln#206]
**Describe the bug** `pycln --all` removes an implicit import from a subpackage.

**To Reproduce** Steps to reproduce the behavior:

1. Take this code snippet:

   ```python
   import json.encoder
   json.loads("1")
   ```

2. Run this Pycln command:
   ```bash
   $ pycln --all example.py
   ```
3. Error traceback or unexpected output (if present):

   ```bash
   example.py:1:0 'import js' was removed! 🔮
   example.py 1 import was removed! 🚀

   All done! 💪 😎
   1 import was removed, 1 file was changed.
   ```

4. Unexpected fixed code (if present):

   >

   ```python
	 
   json.loads("")
   ```

**Expected behavior**:

1.  Description: `--all` still takes into account [[Implicit Imports From Sub-Packages](https://hadialqattan.github.io/pycln/#/?id=implicit-imports-from-sub-packages)](https://hadialqattan.github.io/pycln/#/?id=implicit-imports-from-sub-packages)
2.  Expected output (if present): no imports removed

3.  Expected fixed code (if present): no change

**Environment (please complete the following informations):**

- Python Version: [e.g. Python 3.8] 3.9
- Pycln Version: [e.g. v0.0.1] 2.1.5
- OS Type: [e.g. Linux] macOS

**Additional context** N/A

**Comment by hadialqattan** [comment]
Hey @adamchainz, I see the problem... I've filed a fix in PR(#207). If you don't mind, could you check that it works on your side?

Happy to see you around, 

Thanks.
