### ISSUE TITLE
[BUG] Imports used in deferred annotations unexpectedly cleaned

### ISSUE THREAD

**Issue by loic-simon** [hadialqattan/pycln#208]
**Describe the bug** 

**To Reproduce** 

1. Take this code snippet (`mwe.py`):

   ```python
    from collections.abc import Callable
    from typing import TYPE_CHECKING

    if TYPE_CHECKING:
        from http import HTTPStatus

    is_status_ok: Callable[["HTTPStatus"], None]
   ```

2. Run this Pycln command:
   ```bash
   $ pycln run mwe.py
   ```
3. Error traceback or unexpected output:

   ```bash
      mwe.py:5:4 'from http import HTTPStatus' was removed! 🔮
      mwe.py 1 import was removed! 🚀

    All done! 💪 😎
    1 import was removed, 1 file was changed.
   ```

4. Unexpected fixed code:

   ```python
    from collections.abc import Callable
    from typing import TYPE_CHECKING

    if TYPE_CHECKING:
        pass

    is_status_ok: Callable[["HTTPStatus"], None]
   ```

**Expected behavior**:

1.  Description: The import is detected as used and not clean.
2.  Expected output (if present):

    ```bash
    Looks good! ✨ 🍰 ✨
    1 file left unchanged.
    ```

3.  Expected fixed code: _File is unchanged_

**Environment:**

- Python Version: Python 3.11.1
- Pycln Version: v2.1.6
- OS Type: MacOS 13

**Additional context** The `Callable` seems important here: if you remplace it with `list["HttpStatus"]`, it seems correctly detected and thus not deleted 🤔 

Thanks!

**Comment by hadialqattan** [comment]
Hi @loic-simon, I'm happy to see you around supporting this project...

I took a quick look at the problem and I think that this is an exception only for `typing/collections.abc.Callable` so I provided a fix for that (I'll open a PR ASAP). Is it true that this issue is only with `typing/collections.abc.Callable` or am I missing something?

**Comment by loic-simon** [comment]
Hi @hadialqattan, it looks like it! I tried various other typing "special forms", and all seem to work well except for `Callable`.

Happy to hear you have a fix, thanks for your work with this project!
