### ISSUE TITLE
[BUG] ImportError: cannot import name '_posix_flavour' from 'pathlib' (Python 3.12 compatibility)

### ISSUE THREAD

**Issue by chopeen** [hadialqattan/pycln#221]
https://github.com/hadialqattan/pycln/blob/master/pycln/utils/refactor.py#L5 references fields `_posix_flavour` and `_windows_flavour` that are not available in `pathlib` in Python 3.12 anymore.

```
pycln....................................................................Failed
- hook id: pycln
- exit code: 1
Traceback (most recent call last):
  File "/root/.cache/pre-commit/repog6i_vrbe/py_env-python3/bin/pycln", line 5, in <module>
    from pycln.cli import app
  File "/root/.cache/pre-commit/repog6i_vrbe/py_env-python3/lib/python3.12/site-packages/pycln/cli.py", line 8, in <module>
    from .utils import iou, pathu, refactor, regexu, report
  File "/root/.cache/pre-commit/repog6i_vrbe/py_env-python3/lib/python3.12/site-packages/pycln/utils/refactor.py", line 5, in <module>
    from pathlib import Path, _posix_flavour, _windows_flavour  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name '_posix_flavour' from 'pathlib' (/usr/local/lib/python3.12/pathlib.py)
```

Could the field `_flavour` be used instead?

**Environment:**

- Python Version: 3.12.0
- Pycln Version: 2.3.0
- OS Type: Linux

**Comment by perfa** [comment]
I had a few minutes to look at this, if it helps whoever picks this up. [The underlying change](https://discuss.python.org/t/make-pathlib-extensible/3428) has pretty extensive conversation log, but I suspect that this might be as simple a fix as
```python
if sys.version_info >= (3, 12):
    from pathlib import Path, _flavour
else:
    from pathlib import Path, _posix_flavour, _windows_flavour  # type: ignore
    _flavour = _windows_flavour if ISWIN else _posix_flavour
```
I'll see if I have time to get pycln and it's tests running in the coming days to verify, although I can't promise anything.

**Comment by eduardo-rodrigues** [comment]
Hello. This feature is providing failures to all our Scikit-HEP repos in the pre-commit hooks. Could a patch with the fix be provided asap. That would be cool.

Thank you very much in advance.

**Comment by hadialqattan** [comment]
This isssue has been resolved in PR #224 .. Thanks to @perfa

**Comment by hadialqattan** [comment]
@chopeen @perfa @eduardo-rodrigues 
Please checkout v2.4.0

**Comment by chopeen** [comment]
Works for me! :rocket:
