### ISSUE TITLE
[FEATURE] Python 3.12 types support

### ISSUE THREAD

**Issue by hippalectryon-0** [hadialqattan/pycln#223]
Problem:

python 3.12 valid syntax such as `type vec2 = np.ndarray[(2,), float]` is detected as a SyntaxError by pycln, although it is not.

**Comment by hadialqattan** [comment]
Hey @hippalectryon-0, could you confirm that the master branch fixes this problem please?

Thanks.

**Comment by hadialqattan** [comment]
@hippalectryon-0 please checkout v2.4.0

**Comment by hippalectryon-0** [comment]
I get ``error: cannot format temp.py: Cannot parse: 3:5: type vec2 = np.ndarray[(2,), float]``
