### ISSUE TITLE
[BUG] Spaces inside Literal type annotations break pycln

### ISSUE THREAD

**Issue by zealotous** [hadialqattan/pycln#41]
**Describe the bug** Spaces inside Literal type annotations break pycln.

**To Reproduce** Steps to reproduce the behaviour:

1. Take this code snippet:

   ```python
    # test-pycln.py
    from typing_extensions import Literal
    import math
    
    # spaces inside Literal type annotations break pycln
    LITERAL_WITH_SPACE: Literal["literal with space"] = "literal with space"
    NO_SPACE: Literal["no_space"] = "no_space"
   ```

2. Run this Pycln command:
   ```bash
    $ pipx list | grep pycln
       package pycln 0.0.1b0, Python 3.6.8
    $ mypy test-pycln.py
        Success: no issues found in 1 source file
    $ pycln test-pycln.py
      test-pycln.py .:1:12 SyntaxError: invalid syntax 'literal with space' ⛔
    
    Oh no, there is an error! 💔 ☹️
    1 file left unchanged, 1 file has failed to be cleaned.
   ```

**Expected behavior**:

1.  `pycln` successfully processes the file.
2.  Expected output (if present):
    ```bash
    $ pycln test-pycln.py 
    Looks good! ✨ 🍰 ✨
    1 file changed.
    ```

**Environment (please complete the following information):**

- Python Version: Python 3.6.8 Python 3.8.2
- Pycln Version: 0.0.1b0
- OS Type: Linux, Windows

`pycln` installed into an isolated virtual environment by pipx

**Comment by zealotous** [comment]
https://github.com/hadialqattan/pycln/blob/master/pycln/utils/scan.py#L201-L217
Here Literal[" "] is parsed by ast.parse

The raw idea for a fix https://github.com/zealotous/pycln/blob/literal-w-spaces-fix/pycln/utils/scan.py#L200-L223

**Comment by hadialqattan** [comment]
Thanks a lot for being here and showing your support...❤️

Unfortunately, that's an uncovered bug!

Kindly, plz open a PR with your fix, I'm gonna help you to write the proper test cases!

**Comment by hadialqattan** [comment]
If you don't wanna work on that, don't worry I'm gonna fix it as soon as possible...thx again 🌹
