### ISSUE TITLE
[FEATURE] Keep the original line break

### ISSUE THREAD

**Issue by BoYanZh** [hadialqattan/pycln#47]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I find that after running this tool, the line break are all replaced by CRLF on my windows PC.

**Describe the solution you'd like**

Keep the original format of line break.

**Comment by hadialqattan** [comment]
@BoYanZh Hi, I'm gonna work on that as soon as possible, thanks for being here!

**Comment by hadialqattan** [comment]
https://github.com/hadialqattan/pycln/blob/db98579c0380b333441a6ca3b6ff8c3f6f7b9af0/pycln/utils/refactor.py#L113
After investigating, the problem is `splitlines` in Python uses `CRLF` for WindowsNT and `LF` for Unix-based systems by default!

**Comment by hadialqattan** [comment]
@BoYanZh Please checkout Pycln beta.3 release!

**Comment by BoYanZh** [comment]
Thanks! I really appreciate that.
