### ISSUE TITLE
[BUG] UnicodeEncodeError on line 155 (cli.py) when running on Windows

### ISSUE THREAD

**Issue by matejbasic** [hadialqattan/pycln#54]
Hi, colleague of my mine was unable to run pycln as a pre-commit hook on his Windows machine.
I have tried it myself and it fails with the same error message:

```bash
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 12: character maps to <undefined>
```

Problematic line:
```python
typer.echo(str(reporter), nl=False)
```

I have tried to fix it and encoding it to UTF-8 seems to help:
```python
typer.echo(str(reporter).encode("utf-8"), nl=False)
```

I will prepare PR for this.

**Environment:**

- Python Version: Python 3.9
- Pycln Version: v0.0.2
- OS Type: Windows 10

**Comment by hadialqattan** [comment]
@matejbasic I've created another PR to fix all  non-utf8 terminals issues by reconfiguring the `sys.stdout`&`sys.stderr` encoding to `utf-8`, so, kindly, please test branch `i54-2` on the same environment where the issue has appeared, and please let me know if everything is fine.

Thanks for your help!

**Comment by matejbasic** [comment]
Great, thank you @hadialqattan for the quick response. I have tested it on Windows and it seems to work fine now, my colleague also confirmed this.

Thank you for this great plugin!

**Comment by hadialqattan** [comment]
> Great, thank you @hadialqattan for the quick response. I have tested it on Windows and it seems to work fine now, my colleague also confirmed this.
> 
> Thank you for this great plugin!

I'm happy to hear that from you.

BTW, today I'm gonna release a new version of Pycln which includes the fix (continue working on my PR ~> merge ~> release).
