### ISSUE TITLE
[FEATURE] vscode / pycharm extension

### ISSUE THREAD

**Issue by hexiro** [hadialqattan/pycln#66]
**Is your feature request related to a problem?**
Use of this project isn't always convenient/ visual for the user.

**Describe the solution you'd like**
It would be nice to have an extension for vs code / pycharm. I also believe this will get more eyes on the project.

**Describe alternatives you've considered**
using version control integration would work great, but in my opinion, an extension would be the preferred use case.

**Additional context**
Not sure how hard this is, just a suggestion 😃

**Comment by hadialqattan** [comment]
Hi @Hexiro, I'm happy to see you around, anyway, it's a good idea, I may create a separate repository for a VSCode extension very soon.

**Comment by hexiro** [comment]
sounds like a good idea to me. good luck! 😄

**Comment by hadialqattan** [comment]
[pycln-vscode](https://github.com/hadialqattan/pycln-vscode) (WIP)
