### ISSUE TITLE
[BUG] Recursion Errors

### ISSUE THREAD

**Issue by GameDungeon** [hadialqattan/pycln#71]
Every time I run it it gets stuck in this loop until it gets a precision error: 

>   \pycln\utils\scan.py", line 718, in generic_visit
    self.visit(item)
  File "python39\lib\ast.py", line 407, in visit
    return visitor(node)
  \pycln\utils\scan.py", line 104, in wrapper
    func(self, *args, **kwargs)
  \pycln\utils\scan.py", line 639, in visit_ImportFrom
    node = cast(ast.ImportFrom, expand_import_star(node, self._path))
  \pycln\utils\scan.py", line 855, in expand_import_star
    analyzer.visit(tree)
  File "python39\lib\ast.py", line 407, in visit
    return visitor(node)
  \pycln\utils\scan.py", line 718, in generic_visit
    self.visit(item)
  File "python39\lib\ast.py", line 407, in visit
    return visitor(node)
  \pycln\utils\scan.py", line 104, in wrapper
    func(self, *args, **kwargs)
  \pycln\utils\scan.py", line 639, in visit_ImportFrom
    node = cast(ast.ImportFrom, expand_import_star(node, self._path))
  \pycln\utils\scan.py", line 855, in expand_import_star
  RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by hadialqattan** [comment]
Hi, could you provide me a sample of the code that causes the problem?

**Comment by hadialqattan** [comment]
Hi @GameDungeon, I'm happy to see you around, I did fix the issue, my fix will be applied in the next release (v1.0.4), thanks for the feedback.
