### ISSUE TITLE
[BUG] Fighting my Trailing Commas

### ISSUE THREAD

**Issue by GameDungeon** [hadialqattan/pycln#77]
My projects style use trailing commas.

Due to this pycln does this a lot:
```

--- original/ manim\cli\new\group.py
+++ fixed/ manim\cli\new\group.py
@@ -9,7 +9,7 @@
     add_import_statement,
     copy_template_files,
     get_template_names,
-    get_template_path,
+    get_template_path
 )

```

Could I have an option that stops this.

**Comment by hadialqattan** [comment]
Hi @GameDungeon, 

This option is out of Pycln scope. I believe you should run a formatter (e.g. Black) after running Pycln.

**Comment by hadialqattan** [comment]
Please feel free to comment even after closing the issue...Happy to see you around, thank you.

**Comment by GameDungeon** [comment]
Pycln is making the changes to my file in every import with a trailing comma. I want it to stop that. I don't understand how this is out of Pycln's scope.

**Comment by hadialqattan** [comment]
@GameDungeon Hi again, I apologize for closing this issue without fixing it. I misunderstood you.

\+ I'm working on a fix right now.

\+ Thank you for the feedback. I'm happy to see you around.
