### ISSUE TITLE
Add Python 3.10 Support

### ISSUE THREAD

**Issue by TylerYep** [hadialqattan/pycln#78]
pycln is currently not installable in Python 3.10 via pip:

```
> pip install pycln
ERROR: Could not find a version that satisfies the requirement pycln (from versions: none)
ERROR: No matching distribution found for pycln
```

**Comment by hadialqattan** [comment]
Thanks for notifying me. WIP.

**Comment by hadialqattan** [comment]
Hello @TylerYep, @kreczko, @dbarbier, @fteicht, and @henryiii. I'm sorry for being too late. I was too busy in the last two months. In this message, I want to announce that Python3.10 has been supported in today's release ([v1.1.0](https://github.com/hadialqattan/pycln/releases/tag/v1.1.0)).
