### ISSUE TITLE
[BUG] pycln ignores NOQA on imports with `-a`

### ISSUE THREAD

**Issue by perfa** [hadialqattan/pycln#80]
**Description:** Running pycln with the `-a`, lines with `# NOQA` are removed

**To Reproduce** Steps to reproduce the behavior:

1. Take this code snippet:

```python
from models.blueprint import \
    Blueprint  # NOQA - required for stand-alone runs or sqlalchemy gets lost wrt cross-table reference

print("Test")
```

2. Run this Pycln command:

```bash
   $ pycln -a pycln_test.py
```

3. Error traceback or unexpected output (if present):

```bash
  pycln_test.py:1:0 'from models.blueprint import Blueprint' has removed! 🔮
  pycln_test.py 1 import has removed! 🚀

All done! 💪 😎
1 import has removed, 1 file has changed.
```

4. Unexpected fixed code (if present):

   >

```python


print("Test")
```

**Expected behavior**:

Lines marked NOQA should remain (at least on the lowest aggressivity level)

**Environment (please complete the following informations):**

- Python Version: Python 3.8
- Pycln Version: version 1.0.3
- OS Type: MacOs 11.6 (Big Sur)

**Comment by hadialqattan** [comment]
Hi again @perfa, this issue has been fixed. The fix will take effect in the next release (soon). Thank you for the feedback. I'm happy to see you around.
