### ISSUE TITLE
[TYPO] CLI logs' grammar correction

### ISSUE THREAD

**Issue by pmourlanne** [hadialqattan/pycln#89]
**Describe the bug**

Here's a sample output I get:
```
$> pycln .
  path/to/file.py:34:0 'import time' has removed! 🔮
  path/to/file.py:35:0 'import json' has removed! 🔮
  path/to/file.py 2 imports has removed! 🚀

All done! 💪 😎
2 imports has removed, 1 file has changed, 201 files left unchanged.
```

For each removed import I expect to read "1 import was removed" or "1 import has been removed", not "1 import has removed".  
In the totals (for each file and overall), the plural form of the verb should be handled. I expect to read "2 imports were removed" or "2 imports have been removed", not "2 imports has removed".

**To Reproduce**

Every output behaves this way so it should be easy enough to reproduce :> It's even asserted on in the tests :o

**Expected behavior**

Already talked about above

**Environment (please complete the following informations):**

- Python Version: Python 3.7
- Pycln Version: 1.1.0 (but the issue is present on `master`)
- OS Type: Ubuntu

**Additional context**

I'm not a native English speaker so maybe I'm flat out wrong. Do tell if I am :>  
I'll try and open a PR to fix this :)

**Comment by hadialqattan** [comment]
Hi @pmourlanne, I'm happy to see you around...

Regarding "has/has been/was": Yeah you're right, it should be either "was removed" or "has been removed". Actually, "has been removed" is better than "was removed" coz "has" implies that the imports are no longer exist, but I put "has removed" instead coz "has been removed" is too long.

Regarding singular vs plural: I was too lazy to work on the linguistics of a CLI app.

Thanks for being around.

**Comment by pmourlanne** [comment]
Happy to help :) I should be done with my PR soon :crossed_fingers:
