### ISSUE TITLE
[BUG] Issue when doing `import *` from an empty file

### ISSUE THREAD

**Issue by pmourlanne** [hadialqattan/pycln#91]
**Describe the bug**

`pycln` behaves weirdly when you do a star import of an empty file. I agree it's an edge case, and what am I doing importing from an empty file anyway?  
Still, the behaviour is unexpected, and maybe there's an actual issue behind it all?

**To Reproduce**

1. Create a python package with three files:

`__init__.py`:
   ```python
from .api import *
from .admin import *
   ```

`api.py`:
   ```python
def my_view(request):
    ...
   ```

`admin.py`:
   ```python
# Purposefully left empty
# For example django's `startapp` command will create empty files to put eg. your views
   ```

2. Run this Pycln command:

```bash
$ pycln .
  views/__init__.py:2:0 'from .admin import *' has removed! 🔮

All done! 💪 😎
1 import has removed, 3 files left unchanged.
```

The issue is that nothing is actually removed :ok_woman: Running the same command again yields the same result: report says an import has been removed, but it's still present.

Note that running the same command with `--all`:
```bash
$ pycln . --all
  views/__init__.py:1:0 'from .api import *' has removed! 🔮
  views/__init__.py:2:0 'from .admin import *' has removed! 🔮
  views/__init__.py 2 imports has removed! 🚀

All done! 💪 😎
2 imports has removed, 1 file has changed, 2 files left unchanged.
```
*does* remove the `from .api import *` import, but not the `from .admin import *` one :detective: 

3. Error traceback or unexpected output (if present):

In the default behaviour, I expect the reporting to say that nothing needs to be changed.  
In the `--all` behaviour, I expect both star imports to be removed.

**Expected behavior**:

:point_up: Described above

**Environment (please complete the following informations):**

- Python Version: Python 3.8
- Pycln Version: 1.1.0
- OS Type: Ubuntu

**Additional context** Add any other context about the problem here.

I'll try and look into this myself :eyes:

**Comment by hadialqattan** [comment]
Hi, I see your point. If you don't mind, I'll assign this issue to you if you want to work on it. Could I?

\+ Thanks again for the support!

**Comment by pmourlanne** [comment]
@hadialqattan Sure 👍
