### ISSUE TITLE
[BUG] Unused imports not removed

### ISSUE THREAD

**Issue by denizdogan** [hadialqattan/pycln#96]
**Describe the bug** A clear and concise description of what the bug is.

Pycln doesn't remove two unused imports

**To Reproduce** Steps to reproduce the behavior:

1. Take this code snippet:

   ```python
    import nanoid
    from django.core.validators import MaxValueValidator, MinValueValidator
    from django.db.models import (
        SET_NULL,
        CharField,
        DurationField,
        FileField,
        ForeignKey,
        TimeField,
        UUIDField,
    )
   ```

   In the above, MaxValueValidator, MinValueValidator, and TimeField are all unused.

2. Run this Pycln command:
   ```bash
   $ pycln that_file.py
   ```
3. Error traceback or unexpected output (if present):

   ```bash
    Looks good! ✨ 🍰 ✨
    1 file left unchanged.
   ```

**Expected behavior**:

I expect the unused imports to be removed.

**Environment (please complete the following informations):**

- Python Version: 3.9.10
- Pycln Version: 1.1.0
- OS Type: macOS

**Comment by hadialqattan** [comment]
Hi @denizdogan , did you try to run Pycln with the [-a/--all](https://hadialqattan.github.io/pycln/#/?id=-a-all-flag) flag?

Please let me know if that helps so I can close this issue.

**Comment by hadialqattan** [comment]
Hi again @denizdogan, I did the experiment myself and everything went as expected with the `-a/--all` flag:

```bash
$ pycln x.py --all
  x.py:2:0 'from django.core.validators import MaxValueValidator' has removed! 🔮
  x.py:2:0 'from django.core.validators import MinValueValidator' has removed! 🔮
  x.py:3:0 'from django.db.models import TimeField' has removed! 🔮
  x.py 3 imports has removed! 🚀

All done! 💪 😎
3 imports has removed, 1 file has changed.
```

---
so now I'm gonna close this issue, if that didn't help you, plz feel free to reopen this issue again.

\+ Thanks a lot for being around.
